#!/bin/sh

destination=~/nixos-laptop-config

# ensure folder exists
mkdir -p $destination/nixos

# copy files to repo
for f in $(ls /etc/nixos)
do
        cp -rv /etc/nixos/$f $destination/nixos
done

